name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t py-load-eudravigilance-test .

    - name: Run tests in Docker container
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $GITHUB_WORKSPACE:/app py-load-eudravigilance-test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        # The user of this repo needs to set a CODECOV_TOKEN secret in their repository settings
        token: ${{ secrets.CODECOV_TOKEN }}
